[project]
authors = ["mikedecr <mgdecrescenzo@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "sugar-free-dict-union"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "==3.11"
quarto = "1.6.*"
